version: '3'

services:
  mysqldb:
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - /home/ubuntu/datamysql
    environment:
      MYSQL_DATABASE: spring
      MYSQL_ROOT_PASSWORD:
    networks:
      - database_net
    deploy:
      replicas: 1

networks:
  database_net:
    driver: overlay